PROJECT_NAME := toastboard

EXTRA_COMPONENT_DIRS = $(IDF_PATH)/examples/common_components/protocol_examples_common

EXTRA_COMPONENT_DIRS += \
 components/memfault_port/memfault-firmware-sdk/ports/esp8266_sdk/memfault \
 components/memfault_port/memfault-firmware-sdk/ports/esp8266_sdk/memfault_freertos

include $(IDF_PATH)/make/project.mk

