PROJECT_NAME := toastboard

EXTRA_COMPONENT_DIRS = \
 components/memfault_port/memfault-firmware-sdk/ports/esp8266_sdk/memfault \
 components/memfault_port/memfault-firmware-sdk/ports/esp8266_sdk/memfault_freertos

CFLAGS += -fstack-usage

include $(IDF_PATH)/make/project.mk

